// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Module.proto

package com.las4vc.composevr.protocol;

public final class ModuleOuterClass {
  private ModuleOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ModuleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ComposeVR.Module)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();
  }
  /**
   * Protobuf type {@code ComposeVR.Module}
   */
  public  static final class Module extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ComposeVR.Module)
      ModuleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Module.newBuilder() to construct.
    private Module(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Module() {
      id_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Module(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.las4vc.composevr.protocol.ModuleOuterClass.internal_static_ComposeVR_Module_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.las4vc.composevr.protocol.ModuleOuterClass.internal_static_ComposeVR_Module_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.las4vc.composevr.protocol.ModuleOuterClass.Module.class, com.las4vc.composevr.protocol.ModuleOuterClass.Module.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.las4vc.composevr.protocol.ModuleOuterClass.Module)) {
        return super.equals(obj);
      }
      com.las4vc.composevr.protocol.ModuleOuterClass.Module other = (com.las4vc.composevr.protocol.ModuleOuterClass.Module) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.las4vc.composevr.protocol.ModuleOuterClass.Module parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.las4vc.composevr.protocol.ModuleOuterClass.Module parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.las4vc.composevr.protocol.ModuleOuterClass.Module parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.las4vc.composevr.protocol.ModuleOuterClass.Module parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.las4vc.composevr.protocol.ModuleOuterClass.Module parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.las4vc.composevr.protocol.ModuleOuterClass.Module parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.las4vc.composevr.protocol.ModuleOuterClass.Module parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.las4vc.composevr.protocol.ModuleOuterClass.Module parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.las4vc.composevr.protocol.ModuleOuterClass.Module parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.las4vc.composevr.protocol.ModuleOuterClass.Module parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.las4vc.composevr.protocol.ModuleOuterClass.Module parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.las4vc.composevr.protocol.ModuleOuterClass.Module parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.las4vc.composevr.protocol.ModuleOuterClass.Module prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ComposeVR.Module}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ComposeVR.Module)
        com.las4vc.composevr.protocol.ModuleOuterClass.ModuleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.las4vc.composevr.protocol.ModuleOuterClass.internal_static_ComposeVR_Module_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.las4vc.composevr.protocol.ModuleOuterClass.internal_static_ComposeVR_Module_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.las4vc.composevr.protocol.ModuleOuterClass.Module.class, com.las4vc.composevr.protocol.ModuleOuterClass.Module.Builder.class);
      }

      // Construct using com.las4vc.composevr.protocol.ModuleOuterClass.Module.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.las4vc.composevr.protocol.ModuleOuterClass.internal_static_ComposeVR_Module_descriptor;
      }

      public com.las4vc.composevr.protocol.ModuleOuterClass.Module getDefaultInstanceForType() {
        return com.las4vc.composevr.protocol.ModuleOuterClass.Module.getDefaultInstance();
      }

      public com.las4vc.composevr.protocol.ModuleOuterClass.Module build() {
        com.las4vc.composevr.protocol.ModuleOuterClass.Module result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.las4vc.composevr.protocol.ModuleOuterClass.Module buildPartial() {
        com.las4vc.composevr.protocol.ModuleOuterClass.Module result = new com.las4vc.composevr.protocol.ModuleOuterClass.Module(this);
        result.id_ = id_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.las4vc.composevr.protocol.ModuleOuterClass.Module) {
          return mergeFrom((com.las4vc.composevr.protocol.ModuleOuterClass.Module)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.las4vc.composevr.protocol.ModuleOuterClass.Module other) {
        if (other == com.las4vc.composevr.protocol.ModuleOuterClass.Module.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.las4vc.composevr.protocol.ModuleOuterClass.Module parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.las4vc.composevr.protocol.ModuleOuterClass.Module) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ComposeVR.Module)
    }

    // @@protoc_insertion_point(class_scope:ComposeVR.Module)
    private static final com.las4vc.composevr.protocol.ModuleOuterClass.Module DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.las4vc.composevr.protocol.ModuleOuterClass.Module();
    }

    public static com.las4vc.composevr.protocol.ModuleOuterClass.Module getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Module>
        PARSER = new com.google.protobuf.AbstractParser<Module>() {
      public Module parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Module(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Module> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Module> getParserForType() {
      return PARSER;
    }

    public com.las4vc.composevr.protocol.ModuleOuterClass.Module getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CreateSoundModuleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ComposeVR.CreateSoundModule)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ComposeVR.Module receiver = 1;</code>
     */
    boolean hasReceiver();
    /**
     * <code>.ComposeVR.Module receiver = 1;</code>
     */
    com.las4vc.composevr.protocol.ModuleOuterClass.Module getReceiver();
    /**
     * <code>.ComposeVR.Module receiver = 1;</code>
     */
    com.las4vc.composevr.protocol.ModuleOuterClass.ModuleOrBuilder getReceiverOrBuilder();

    /**
     * <code>.ComposeVR.Module sender = 2;</code>
     */
    boolean hasSender();
    /**
     * <code>.ComposeVR.Module sender = 2;</code>
     */
    com.las4vc.composevr.protocol.ModuleOuterClass.Module getSender();
    /**
     * <code>.ComposeVR.Module sender = 2;</code>
     */
    com.las4vc.composevr.protocol.ModuleOuterClass.ModuleOrBuilder getSenderOrBuilder();
  }
  /**
   * Protobuf type {@code ComposeVR.CreateSoundModule}
   */
  public  static final class CreateSoundModule extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ComposeVR.CreateSoundModule)
      CreateSoundModuleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CreateSoundModule.newBuilder() to construct.
    private CreateSoundModule(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CreateSoundModule() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CreateSoundModule(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.las4vc.composevr.protocol.ModuleOuterClass.Module.Builder subBuilder = null;
              if (receiver_ != null) {
                subBuilder = receiver_.toBuilder();
              }
              receiver_ = input.readMessage(com.las4vc.composevr.protocol.ModuleOuterClass.Module.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(receiver_);
                receiver_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.las4vc.composevr.protocol.ModuleOuterClass.Module.Builder subBuilder = null;
              if (sender_ != null) {
                subBuilder = sender_.toBuilder();
              }
              sender_ = input.readMessage(com.las4vc.composevr.protocol.ModuleOuterClass.Module.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(sender_);
                sender_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.las4vc.composevr.protocol.ModuleOuterClass.internal_static_ComposeVR_CreateSoundModule_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.las4vc.composevr.protocol.ModuleOuterClass.internal_static_ComposeVR_CreateSoundModule_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.las4vc.composevr.protocol.ModuleOuterClass.CreateSoundModule.class, com.las4vc.composevr.protocol.ModuleOuterClass.CreateSoundModule.Builder.class);
    }

    public static final int RECEIVER_FIELD_NUMBER = 1;
    private com.las4vc.composevr.protocol.ModuleOuterClass.Module receiver_;
    /**
     * <code>.ComposeVR.Module receiver = 1;</code>
     */
    public boolean hasReceiver() {
      return receiver_ != null;
    }
    /**
     * <code>.ComposeVR.Module receiver = 1;</code>
     */
    public com.las4vc.composevr.protocol.ModuleOuterClass.Module getReceiver() {
      return receiver_ == null ? com.las4vc.composevr.protocol.ModuleOuterClass.Module.getDefaultInstance() : receiver_;
    }
    /**
     * <code>.ComposeVR.Module receiver = 1;</code>
     */
    public com.las4vc.composevr.protocol.ModuleOuterClass.ModuleOrBuilder getReceiverOrBuilder() {
      return getReceiver();
    }

    public static final int SENDER_FIELD_NUMBER = 2;
    private com.las4vc.composevr.protocol.ModuleOuterClass.Module sender_;
    /**
     * <code>.ComposeVR.Module sender = 2;</code>
     */
    public boolean hasSender() {
      return sender_ != null;
    }
    /**
     * <code>.ComposeVR.Module sender = 2;</code>
     */
    public com.las4vc.composevr.protocol.ModuleOuterClass.Module getSender() {
      return sender_ == null ? com.las4vc.composevr.protocol.ModuleOuterClass.Module.getDefaultInstance() : sender_;
    }
    /**
     * <code>.ComposeVR.Module sender = 2;</code>
     */
    public com.las4vc.composevr.protocol.ModuleOuterClass.ModuleOrBuilder getSenderOrBuilder() {
      return getSender();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (receiver_ != null) {
        output.writeMessage(1, getReceiver());
      }
      if (sender_ != null) {
        output.writeMessage(2, getSender());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (receiver_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getReceiver());
      }
      if (sender_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getSender());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.las4vc.composevr.protocol.ModuleOuterClass.CreateSoundModule)) {
        return super.equals(obj);
      }
      com.las4vc.composevr.protocol.ModuleOuterClass.CreateSoundModule other = (com.las4vc.composevr.protocol.ModuleOuterClass.CreateSoundModule) obj;

      boolean result = true;
      result = result && (hasReceiver() == other.hasReceiver());
      if (hasReceiver()) {
        result = result && getReceiver()
            .equals(other.getReceiver());
      }
      result = result && (hasSender() == other.hasSender());
      if (hasSender()) {
        result = result && getSender()
            .equals(other.getSender());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasReceiver()) {
        hash = (37 * hash) + RECEIVER_FIELD_NUMBER;
        hash = (53 * hash) + getReceiver().hashCode();
      }
      if (hasSender()) {
        hash = (37 * hash) + SENDER_FIELD_NUMBER;
        hash = (53 * hash) + getSender().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.las4vc.composevr.protocol.ModuleOuterClass.CreateSoundModule parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.las4vc.composevr.protocol.ModuleOuterClass.CreateSoundModule parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.las4vc.composevr.protocol.ModuleOuterClass.CreateSoundModule parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.las4vc.composevr.protocol.ModuleOuterClass.CreateSoundModule parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.las4vc.composevr.protocol.ModuleOuterClass.CreateSoundModule parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.las4vc.composevr.protocol.ModuleOuterClass.CreateSoundModule parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.las4vc.composevr.protocol.ModuleOuterClass.CreateSoundModule parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.las4vc.composevr.protocol.ModuleOuterClass.CreateSoundModule parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.las4vc.composevr.protocol.ModuleOuterClass.CreateSoundModule parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.las4vc.composevr.protocol.ModuleOuterClass.CreateSoundModule parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.las4vc.composevr.protocol.ModuleOuterClass.CreateSoundModule parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.las4vc.composevr.protocol.ModuleOuterClass.CreateSoundModule parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.las4vc.composevr.protocol.ModuleOuterClass.CreateSoundModule prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ComposeVR.CreateSoundModule}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ComposeVR.CreateSoundModule)
        com.las4vc.composevr.protocol.ModuleOuterClass.CreateSoundModuleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.las4vc.composevr.protocol.ModuleOuterClass.internal_static_ComposeVR_CreateSoundModule_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.las4vc.composevr.protocol.ModuleOuterClass.internal_static_ComposeVR_CreateSoundModule_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.las4vc.composevr.protocol.ModuleOuterClass.CreateSoundModule.class, com.las4vc.composevr.protocol.ModuleOuterClass.CreateSoundModule.Builder.class);
      }

      // Construct using com.las4vc.composevr.protocol.ModuleOuterClass.CreateSoundModule.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (receiverBuilder_ == null) {
          receiver_ = null;
        } else {
          receiver_ = null;
          receiverBuilder_ = null;
        }
        if (senderBuilder_ == null) {
          sender_ = null;
        } else {
          sender_ = null;
          senderBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.las4vc.composevr.protocol.ModuleOuterClass.internal_static_ComposeVR_CreateSoundModule_descriptor;
      }

      public com.las4vc.composevr.protocol.ModuleOuterClass.CreateSoundModule getDefaultInstanceForType() {
        return com.las4vc.composevr.protocol.ModuleOuterClass.CreateSoundModule.getDefaultInstance();
      }

      public com.las4vc.composevr.protocol.ModuleOuterClass.CreateSoundModule build() {
        com.las4vc.composevr.protocol.ModuleOuterClass.CreateSoundModule result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.las4vc.composevr.protocol.ModuleOuterClass.CreateSoundModule buildPartial() {
        com.las4vc.composevr.protocol.ModuleOuterClass.CreateSoundModule result = new com.las4vc.composevr.protocol.ModuleOuterClass.CreateSoundModule(this);
        if (receiverBuilder_ == null) {
          result.receiver_ = receiver_;
        } else {
          result.receiver_ = receiverBuilder_.build();
        }
        if (senderBuilder_ == null) {
          result.sender_ = sender_;
        } else {
          result.sender_ = senderBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.las4vc.composevr.protocol.ModuleOuterClass.CreateSoundModule) {
          return mergeFrom((com.las4vc.composevr.protocol.ModuleOuterClass.CreateSoundModule)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.las4vc.composevr.protocol.ModuleOuterClass.CreateSoundModule other) {
        if (other == com.las4vc.composevr.protocol.ModuleOuterClass.CreateSoundModule.getDefaultInstance()) return this;
        if (other.hasReceiver()) {
          mergeReceiver(other.getReceiver());
        }
        if (other.hasSender()) {
          mergeSender(other.getSender());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.las4vc.composevr.protocol.ModuleOuterClass.CreateSoundModule parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.las4vc.composevr.protocol.ModuleOuterClass.CreateSoundModule) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.las4vc.composevr.protocol.ModuleOuterClass.Module receiver_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.las4vc.composevr.protocol.ModuleOuterClass.Module, com.las4vc.composevr.protocol.ModuleOuterClass.Module.Builder, com.las4vc.composevr.protocol.ModuleOuterClass.ModuleOrBuilder> receiverBuilder_;
      /**
       * <code>.ComposeVR.Module receiver = 1;</code>
       */
      public boolean hasReceiver() {
        return receiverBuilder_ != null || receiver_ != null;
      }
      /**
       * <code>.ComposeVR.Module receiver = 1;</code>
       */
      public com.las4vc.composevr.protocol.ModuleOuterClass.Module getReceiver() {
        if (receiverBuilder_ == null) {
          return receiver_ == null ? com.las4vc.composevr.protocol.ModuleOuterClass.Module.getDefaultInstance() : receiver_;
        } else {
          return receiverBuilder_.getMessage();
        }
      }
      /**
       * <code>.ComposeVR.Module receiver = 1;</code>
       */
      public Builder setReceiver(com.las4vc.composevr.protocol.ModuleOuterClass.Module value) {
        if (receiverBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          receiver_ = value;
          onChanged();
        } else {
          receiverBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.ComposeVR.Module receiver = 1;</code>
       */
      public Builder setReceiver(
          com.las4vc.composevr.protocol.ModuleOuterClass.Module.Builder builderForValue) {
        if (receiverBuilder_ == null) {
          receiver_ = builderForValue.build();
          onChanged();
        } else {
          receiverBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.ComposeVR.Module receiver = 1;</code>
       */
      public Builder mergeReceiver(com.las4vc.composevr.protocol.ModuleOuterClass.Module value) {
        if (receiverBuilder_ == null) {
          if (receiver_ != null) {
            receiver_ =
              com.las4vc.composevr.protocol.ModuleOuterClass.Module.newBuilder(receiver_).mergeFrom(value).buildPartial();
          } else {
            receiver_ = value;
          }
          onChanged();
        } else {
          receiverBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.ComposeVR.Module receiver = 1;</code>
       */
      public Builder clearReceiver() {
        if (receiverBuilder_ == null) {
          receiver_ = null;
          onChanged();
        } else {
          receiver_ = null;
          receiverBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.ComposeVR.Module receiver = 1;</code>
       */
      public com.las4vc.composevr.protocol.ModuleOuterClass.Module.Builder getReceiverBuilder() {
        
        onChanged();
        return getReceiverFieldBuilder().getBuilder();
      }
      /**
       * <code>.ComposeVR.Module receiver = 1;</code>
       */
      public com.las4vc.composevr.protocol.ModuleOuterClass.ModuleOrBuilder getReceiverOrBuilder() {
        if (receiverBuilder_ != null) {
          return receiverBuilder_.getMessageOrBuilder();
        } else {
          return receiver_ == null ?
              com.las4vc.composevr.protocol.ModuleOuterClass.Module.getDefaultInstance() : receiver_;
        }
      }
      /**
       * <code>.ComposeVR.Module receiver = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.las4vc.composevr.protocol.ModuleOuterClass.Module, com.las4vc.composevr.protocol.ModuleOuterClass.Module.Builder, com.las4vc.composevr.protocol.ModuleOuterClass.ModuleOrBuilder> 
          getReceiverFieldBuilder() {
        if (receiverBuilder_ == null) {
          receiverBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.las4vc.composevr.protocol.ModuleOuterClass.Module, com.las4vc.composevr.protocol.ModuleOuterClass.Module.Builder, com.las4vc.composevr.protocol.ModuleOuterClass.ModuleOrBuilder>(
                  getReceiver(),
                  getParentForChildren(),
                  isClean());
          receiver_ = null;
        }
        return receiverBuilder_;
      }

      private com.las4vc.composevr.protocol.ModuleOuterClass.Module sender_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.las4vc.composevr.protocol.ModuleOuterClass.Module, com.las4vc.composevr.protocol.ModuleOuterClass.Module.Builder, com.las4vc.composevr.protocol.ModuleOuterClass.ModuleOrBuilder> senderBuilder_;
      /**
       * <code>.ComposeVR.Module sender = 2;</code>
       */
      public boolean hasSender() {
        return senderBuilder_ != null || sender_ != null;
      }
      /**
       * <code>.ComposeVR.Module sender = 2;</code>
       */
      public com.las4vc.composevr.protocol.ModuleOuterClass.Module getSender() {
        if (senderBuilder_ == null) {
          return sender_ == null ? com.las4vc.composevr.protocol.ModuleOuterClass.Module.getDefaultInstance() : sender_;
        } else {
          return senderBuilder_.getMessage();
        }
      }
      /**
       * <code>.ComposeVR.Module sender = 2;</code>
       */
      public Builder setSender(com.las4vc.composevr.protocol.ModuleOuterClass.Module value) {
        if (senderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sender_ = value;
          onChanged();
        } else {
          senderBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.ComposeVR.Module sender = 2;</code>
       */
      public Builder setSender(
          com.las4vc.composevr.protocol.ModuleOuterClass.Module.Builder builderForValue) {
        if (senderBuilder_ == null) {
          sender_ = builderForValue.build();
          onChanged();
        } else {
          senderBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.ComposeVR.Module sender = 2;</code>
       */
      public Builder mergeSender(com.las4vc.composevr.protocol.ModuleOuterClass.Module value) {
        if (senderBuilder_ == null) {
          if (sender_ != null) {
            sender_ =
              com.las4vc.composevr.protocol.ModuleOuterClass.Module.newBuilder(sender_).mergeFrom(value).buildPartial();
          } else {
            sender_ = value;
          }
          onChanged();
        } else {
          senderBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.ComposeVR.Module sender = 2;</code>
       */
      public Builder clearSender() {
        if (senderBuilder_ == null) {
          sender_ = null;
          onChanged();
        } else {
          sender_ = null;
          senderBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.ComposeVR.Module sender = 2;</code>
       */
      public com.las4vc.composevr.protocol.ModuleOuterClass.Module.Builder getSenderBuilder() {
        
        onChanged();
        return getSenderFieldBuilder().getBuilder();
      }
      /**
       * <code>.ComposeVR.Module sender = 2;</code>
       */
      public com.las4vc.composevr.protocol.ModuleOuterClass.ModuleOrBuilder getSenderOrBuilder() {
        if (senderBuilder_ != null) {
          return senderBuilder_.getMessageOrBuilder();
        } else {
          return sender_ == null ?
              com.las4vc.composevr.protocol.ModuleOuterClass.Module.getDefaultInstance() : sender_;
        }
      }
      /**
       * <code>.ComposeVR.Module sender = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.las4vc.composevr.protocol.ModuleOuterClass.Module, com.las4vc.composevr.protocol.ModuleOuterClass.Module.Builder, com.las4vc.composevr.protocol.ModuleOuterClass.ModuleOrBuilder> 
          getSenderFieldBuilder() {
        if (senderBuilder_ == null) {
          senderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.las4vc.composevr.protocol.ModuleOuterClass.Module, com.las4vc.composevr.protocol.ModuleOuterClass.Module.Builder, com.las4vc.composevr.protocol.ModuleOuterClass.ModuleOrBuilder>(
                  getSender(),
                  getParentForChildren(),
                  isClean());
          sender_ = null;
        }
        return senderBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ComposeVR.CreateSoundModule)
    }

    // @@protoc_insertion_point(class_scope:ComposeVR.CreateSoundModule)
    private static final com.las4vc.composevr.protocol.ModuleOuterClass.CreateSoundModule DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.las4vc.composevr.protocol.ModuleOuterClass.CreateSoundModule();
    }

    public static com.las4vc.composevr.protocol.ModuleOuterClass.CreateSoundModule getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CreateSoundModule>
        PARSER = new com.google.protobuf.AbstractParser<CreateSoundModule>() {
      public CreateSoundModule parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CreateSoundModule(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CreateSoundModule> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CreateSoundModule> getParserForType() {
      return PARSER;
    }

    public com.las4vc.composevr.protocol.ModuleOuterClass.CreateSoundModule getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OnSoundModuleCreatedOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ComposeVR.OnSoundModuleCreated)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ComposeVR.Module receiver = 1;</code>
     */
    boolean hasReceiver();
    /**
     * <code>.ComposeVR.Module receiver = 1;</code>
     */
    com.las4vc.composevr.protocol.ModuleOuterClass.Module getReceiver();
    /**
     * <code>.ComposeVR.Module receiver = 1;</code>
     */
    com.las4vc.composevr.protocol.ModuleOuterClass.ModuleOrBuilder getReceiverOrBuilder();
  }
  /**
   * Protobuf type {@code ComposeVR.OnSoundModuleCreated}
   */
  public  static final class OnSoundModuleCreated extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ComposeVR.OnSoundModuleCreated)
      OnSoundModuleCreatedOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OnSoundModuleCreated.newBuilder() to construct.
    private OnSoundModuleCreated(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OnSoundModuleCreated() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OnSoundModuleCreated(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.las4vc.composevr.protocol.ModuleOuterClass.Module.Builder subBuilder = null;
              if (receiver_ != null) {
                subBuilder = receiver_.toBuilder();
              }
              receiver_ = input.readMessage(com.las4vc.composevr.protocol.ModuleOuterClass.Module.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(receiver_);
                receiver_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.las4vc.composevr.protocol.ModuleOuterClass.internal_static_ComposeVR_OnSoundModuleCreated_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.las4vc.composevr.protocol.ModuleOuterClass.internal_static_ComposeVR_OnSoundModuleCreated_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.las4vc.composevr.protocol.ModuleOuterClass.OnSoundModuleCreated.class, com.las4vc.composevr.protocol.ModuleOuterClass.OnSoundModuleCreated.Builder.class);
    }

    public static final int RECEIVER_FIELD_NUMBER = 1;
    private com.las4vc.composevr.protocol.ModuleOuterClass.Module receiver_;
    /**
     * <code>.ComposeVR.Module receiver = 1;</code>
     */
    public boolean hasReceiver() {
      return receiver_ != null;
    }
    /**
     * <code>.ComposeVR.Module receiver = 1;</code>
     */
    public com.las4vc.composevr.protocol.ModuleOuterClass.Module getReceiver() {
      return receiver_ == null ? com.las4vc.composevr.protocol.ModuleOuterClass.Module.getDefaultInstance() : receiver_;
    }
    /**
     * <code>.ComposeVR.Module receiver = 1;</code>
     */
    public com.las4vc.composevr.protocol.ModuleOuterClass.ModuleOrBuilder getReceiverOrBuilder() {
      return getReceiver();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (receiver_ != null) {
        output.writeMessage(1, getReceiver());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (receiver_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getReceiver());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.las4vc.composevr.protocol.ModuleOuterClass.OnSoundModuleCreated)) {
        return super.equals(obj);
      }
      com.las4vc.composevr.protocol.ModuleOuterClass.OnSoundModuleCreated other = (com.las4vc.composevr.protocol.ModuleOuterClass.OnSoundModuleCreated) obj;

      boolean result = true;
      result = result && (hasReceiver() == other.hasReceiver());
      if (hasReceiver()) {
        result = result && getReceiver()
            .equals(other.getReceiver());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasReceiver()) {
        hash = (37 * hash) + RECEIVER_FIELD_NUMBER;
        hash = (53 * hash) + getReceiver().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.las4vc.composevr.protocol.ModuleOuterClass.OnSoundModuleCreated parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.las4vc.composevr.protocol.ModuleOuterClass.OnSoundModuleCreated parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.las4vc.composevr.protocol.ModuleOuterClass.OnSoundModuleCreated parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.las4vc.composevr.protocol.ModuleOuterClass.OnSoundModuleCreated parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.las4vc.composevr.protocol.ModuleOuterClass.OnSoundModuleCreated parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.las4vc.composevr.protocol.ModuleOuterClass.OnSoundModuleCreated parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.las4vc.composevr.protocol.ModuleOuterClass.OnSoundModuleCreated parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.las4vc.composevr.protocol.ModuleOuterClass.OnSoundModuleCreated parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.las4vc.composevr.protocol.ModuleOuterClass.OnSoundModuleCreated parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.las4vc.composevr.protocol.ModuleOuterClass.OnSoundModuleCreated parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.las4vc.composevr.protocol.ModuleOuterClass.OnSoundModuleCreated parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.las4vc.composevr.protocol.ModuleOuterClass.OnSoundModuleCreated parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.las4vc.composevr.protocol.ModuleOuterClass.OnSoundModuleCreated prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ComposeVR.OnSoundModuleCreated}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ComposeVR.OnSoundModuleCreated)
        com.las4vc.composevr.protocol.ModuleOuterClass.OnSoundModuleCreatedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.las4vc.composevr.protocol.ModuleOuterClass.internal_static_ComposeVR_OnSoundModuleCreated_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.las4vc.composevr.protocol.ModuleOuterClass.internal_static_ComposeVR_OnSoundModuleCreated_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.las4vc.composevr.protocol.ModuleOuterClass.OnSoundModuleCreated.class, com.las4vc.composevr.protocol.ModuleOuterClass.OnSoundModuleCreated.Builder.class);
      }

      // Construct using com.las4vc.composevr.protocol.ModuleOuterClass.OnSoundModuleCreated.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (receiverBuilder_ == null) {
          receiver_ = null;
        } else {
          receiver_ = null;
          receiverBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.las4vc.composevr.protocol.ModuleOuterClass.internal_static_ComposeVR_OnSoundModuleCreated_descriptor;
      }

      public com.las4vc.composevr.protocol.ModuleOuterClass.OnSoundModuleCreated getDefaultInstanceForType() {
        return com.las4vc.composevr.protocol.ModuleOuterClass.OnSoundModuleCreated.getDefaultInstance();
      }

      public com.las4vc.composevr.protocol.ModuleOuterClass.OnSoundModuleCreated build() {
        com.las4vc.composevr.protocol.ModuleOuterClass.OnSoundModuleCreated result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.las4vc.composevr.protocol.ModuleOuterClass.OnSoundModuleCreated buildPartial() {
        com.las4vc.composevr.protocol.ModuleOuterClass.OnSoundModuleCreated result = new com.las4vc.composevr.protocol.ModuleOuterClass.OnSoundModuleCreated(this);
        if (receiverBuilder_ == null) {
          result.receiver_ = receiver_;
        } else {
          result.receiver_ = receiverBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.las4vc.composevr.protocol.ModuleOuterClass.OnSoundModuleCreated) {
          return mergeFrom((com.las4vc.composevr.protocol.ModuleOuterClass.OnSoundModuleCreated)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.las4vc.composevr.protocol.ModuleOuterClass.OnSoundModuleCreated other) {
        if (other == com.las4vc.composevr.protocol.ModuleOuterClass.OnSoundModuleCreated.getDefaultInstance()) return this;
        if (other.hasReceiver()) {
          mergeReceiver(other.getReceiver());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.las4vc.composevr.protocol.ModuleOuterClass.OnSoundModuleCreated parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.las4vc.composevr.protocol.ModuleOuterClass.OnSoundModuleCreated) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.las4vc.composevr.protocol.ModuleOuterClass.Module receiver_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.las4vc.composevr.protocol.ModuleOuterClass.Module, com.las4vc.composevr.protocol.ModuleOuterClass.Module.Builder, com.las4vc.composevr.protocol.ModuleOuterClass.ModuleOrBuilder> receiverBuilder_;
      /**
       * <code>.ComposeVR.Module receiver = 1;</code>
       */
      public boolean hasReceiver() {
        return receiverBuilder_ != null || receiver_ != null;
      }
      /**
       * <code>.ComposeVR.Module receiver = 1;</code>
       */
      public com.las4vc.composevr.protocol.ModuleOuterClass.Module getReceiver() {
        if (receiverBuilder_ == null) {
          return receiver_ == null ? com.las4vc.composevr.protocol.ModuleOuterClass.Module.getDefaultInstance() : receiver_;
        } else {
          return receiverBuilder_.getMessage();
        }
      }
      /**
       * <code>.ComposeVR.Module receiver = 1;</code>
       */
      public Builder setReceiver(com.las4vc.composevr.protocol.ModuleOuterClass.Module value) {
        if (receiverBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          receiver_ = value;
          onChanged();
        } else {
          receiverBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.ComposeVR.Module receiver = 1;</code>
       */
      public Builder setReceiver(
          com.las4vc.composevr.protocol.ModuleOuterClass.Module.Builder builderForValue) {
        if (receiverBuilder_ == null) {
          receiver_ = builderForValue.build();
          onChanged();
        } else {
          receiverBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.ComposeVR.Module receiver = 1;</code>
       */
      public Builder mergeReceiver(com.las4vc.composevr.protocol.ModuleOuterClass.Module value) {
        if (receiverBuilder_ == null) {
          if (receiver_ != null) {
            receiver_ =
              com.las4vc.composevr.protocol.ModuleOuterClass.Module.newBuilder(receiver_).mergeFrom(value).buildPartial();
          } else {
            receiver_ = value;
          }
          onChanged();
        } else {
          receiverBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.ComposeVR.Module receiver = 1;</code>
       */
      public Builder clearReceiver() {
        if (receiverBuilder_ == null) {
          receiver_ = null;
          onChanged();
        } else {
          receiver_ = null;
          receiverBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.ComposeVR.Module receiver = 1;</code>
       */
      public com.las4vc.composevr.protocol.ModuleOuterClass.Module.Builder getReceiverBuilder() {
        
        onChanged();
        return getReceiverFieldBuilder().getBuilder();
      }
      /**
       * <code>.ComposeVR.Module receiver = 1;</code>
       */
      public com.las4vc.composevr.protocol.ModuleOuterClass.ModuleOrBuilder getReceiverOrBuilder() {
        if (receiverBuilder_ != null) {
          return receiverBuilder_.getMessageOrBuilder();
        } else {
          return receiver_ == null ?
              com.las4vc.composevr.protocol.ModuleOuterClass.Module.getDefaultInstance() : receiver_;
        }
      }
      /**
       * <code>.ComposeVR.Module receiver = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.las4vc.composevr.protocol.ModuleOuterClass.Module, com.las4vc.composevr.protocol.ModuleOuterClass.Module.Builder, com.las4vc.composevr.protocol.ModuleOuterClass.ModuleOrBuilder> 
          getReceiverFieldBuilder() {
        if (receiverBuilder_ == null) {
          receiverBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.las4vc.composevr.protocol.ModuleOuterClass.Module, com.las4vc.composevr.protocol.ModuleOuterClass.Module.Builder, com.las4vc.composevr.protocol.ModuleOuterClass.ModuleOrBuilder>(
                  getReceiver(),
                  getParentForChildren(),
                  isClean());
          receiver_ = null;
        }
        return receiverBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ComposeVR.OnSoundModuleCreated)
    }

    // @@protoc_insertion_point(class_scope:ComposeVR.OnSoundModuleCreated)
    private static final com.las4vc.composevr.protocol.ModuleOuterClass.OnSoundModuleCreated DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.las4vc.composevr.protocol.ModuleOuterClass.OnSoundModuleCreated();
    }

    public static com.las4vc.composevr.protocol.ModuleOuterClass.OnSoundModuleCreated getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OnSoundModuleCreated>
        PARSER = new com.google.protobuf.AbstractParser<OnSoundModuleCreated>() {
      public OnSoundModuleCreated parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OnSoundModuleCreated(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OnSoundModuleCreated> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OnSoundModuleCreated> getParserForType() {
      return PARSER;
    }

    public com.las4vc.composevr.protocol.ModuleOuterClass.OnSoundModuleCreated getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ComposeVR_Module_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ComposeVR_Module_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ComposeVR_CreateSoundModule_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ComposeVR_CreateSoundModule_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ComposeVR_OnSoundModuleCreated_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ComposeVR_OnSoundModuleCreated_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Module.proto\022\tComposeVR\"\024\n\006Module\022\n\n\002i" +
      "d\030\001 \001(\t\"[\n\021CreateSoundModule\022#\n\010receiver" +
      "\030\001 \001(\0132\021.ComposeVR.Module\022!\n\006sender\030\002 \001(" +
      "\0132\021.ComposeVR.Module\";\n\024OnSoundModuleCre" +
      "ated\022#\n\010receiver\030\001 \001(\0132\021.ComposeVR.Modul" +
      "eB;\n\035com.las4vc.composevr.protocol\252\002\031Com" +
      "poseVR.Protocol.Moduleb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ComposeVR_Module_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ComposeVR_Module_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ComposeVR_Module_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_ComposeVR_CreateSoundModule_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ComposeVR_CreateSoundModule_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ComposeVR_CreateSoundModule_descriptor,
        new java.lang.String[] { "Receiver", "Sender", });
    internal_static_ComposeVR_OnSoundModuleCreated_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ComposeVR_OnSoundModuleCreated_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ComposeVR_OnSoundModuleCreated_descriptor,
        new java.lang.String[] { "Receiver", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
