// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Module.proto

package com.las4vc.composevr.protocol;

public final class Module {
  private Module() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CreateSoundModuleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ComposeVR.CreateSoundModule)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string sender_id = 1;</code>
     */
    java.lang.String getSenderId();
    /**
     * <code>string sender_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getSenderIdBytes();
  }
  /**
   * Protobuf type {@code ComposeVR.CreateSoundModule}
   */
  public  static final class CreateSoundModule extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ComposeVR.CreateSoundModule)
      CreateSoundModuleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CreateSoundModule.newBuilder() to construct.
    private CreateSoundModule(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CreateSoundModule() {
      senderId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CreateSoundModule(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              senderId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.las4vc.composevr.protocol.Module.internal_static_ComposeVR_CreateSoundModule_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.las4vc.composevr.protocol.Module.internal_static_ComposeVR_CreateSoundModule_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.las4vc.composevr.protocol.Module.CreateSoundModule.class, com.las4vc.composevr.protocol.Module.CreateSoundModule.Builder.class);
    }

    public static final int SENDER_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object senderId_;
    /**
     * <code>string sender_id = 1;</code>
     */
    public java.lang.String getSenderId() {
      java.lang.Object ref = senderId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderId_ = s;
        return s;
      }
    }
    /**
     * <code>string sender_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSenderIdBytes() {
      java.lang.Object ref = senderId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSenderIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, senderId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSenderIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, senderId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.las4vc.composevr.protocol.Module.CreateSoundModule)) {
        return super.equals(obj);
      }
      com.las4vc.composevr.protocol.Module.CreateSoundModule other = (com.las4vc.composevr.protocol.Module.CreateSoundModule) obj;

      boolean result = true;
      result = result && getSenderId()
          .equals(other.getSenderId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SENDER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSenderId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.las4vc.composevr.protocol.Module.CreateSoundModule parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.las4vc.composevr.protocol.Module.CreateSoundModule parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.las4vc.composevr.protocol.Module.CreateSoundModule parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.las4vc.composevr.protocol.Module.CreateSoundModule parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.las4vc.composevr.protocol.Module.CreateSoundModule parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.las4vc.composevr.protocol.Module.CreateSoundModule parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.las4vc.composevr.protocol.Module.CreateSoundModule parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.las4vc.composevr.protocol.Module.CreateSoundModule parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.las4vc.composevr.protocol.Module.CreateSoundModule parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.las4vc.composevr.protocol.Module.CreateSoundModule parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.las4vc.composevr.protocol.Module.CreateSoundModule parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.las4vc.composevr.protocol.Module.CreateSoundModule parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.las4vc.composevr.protocol.Module.CreateSoundModule prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ComposeVR.CreateSoundModule}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ComposeVR.CreateSoundModule)
        com.las4vc.composevr.protocol.Module.CreateSoundModuleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.las4vc.composevr.protocol.Module.internal_static_ComposeVR_CreateSoundModule_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.las4vc.composevr.protocol.Module.internal_static_ComposeVR_CreateSoundModule_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.las4vc.composevr.protocol.Module.CreateSoundModule.class, com.las4vc.composevr.protocol.Module.CreateSoundModule.Builder.class);
      }

      // Construct using com.las4vc.composevr.protocol.Module.CreateSoundModule.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        senderId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.las4vc.composevr.protocol.Module.internal_static_ComposeVR_CreateSoundModule_descriptor;
      }

      public com.las4vc.composevr.protocol.Module.CreateSoundModule getDefaultInstanceForType() {
        return com.las4vc.composevr.protocol.Module.CreateSoundModule.getDefaultInstance();
      }

      public com.las4vc.composevr.protocol.Module.CreateSoundModule build() {
        com.las4vc.composevr.protocol.Module.CreateSoundModule result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.las4vc.composevr.protocol.Module.CreateSoundModule buildPartial() {
        com.las4vc.composevr.protocol.Module.CreateSoundModule result = new com.las4vc.composevr.protocol.Module.CreateSoundModule(this);
        result.senderId_ = senderId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.las4vc.composevr.protocol.Module.CreateSoundModule) {
          return mergeFrom((com.las4vc.composevr.protocol.Module.CreateSoundModule)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.las4vc.composevr.protocol.Module.CreateSoundModule other) {
        if (other == com.las4vc.composevr.protocol.Module.CreateSoundModule.getDefaultInstance()) return this;
        if (!other.getSenderId().isEmpty()) {
          senderId_ = other.senderId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.las4vc.composevr.protocol.Module.CreateSoundModule parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.las4vc.composevr.protocol.Module.CreateSoundModule) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object senderId_ = "";
      /**
       * <code>string sender_id = 1;</code>
       */
      public java.lang.String getSenderId() {
        java.lang.Object ref = senderId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          senderId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sender_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSenderIdBytes() {
        java.lang.Object ref = senderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sender_id = 1;</code>
       */
      public Builder setSenderId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        senderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sender_id = 1;</code>
       */
      public Builder clearSenderId() {
        
        senderId_ = getDefaultInstance().getSenderId();
        onChanged();
        return this;
      }
      /**
       * <code>string sender_id = 1;</code>
       */
      public Builder setSenderIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        senderId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ComposeVR.CreateSoundModule)
    }

    // @@protoc_insertion_point(class_scope:ComposeVR.CreateSoundModule)
    private static final com.las4vc.composevr.protocol.Module.CreateSoundModule DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.las4vc.composevr.protocol.Module.CreateSoundModule();
    }

    public static com.las4vc.composevr.protocol.Module.CreateSoundModule getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CreateSoundModule>
        PARSER = new com.google.protobuf.AbstractParser<CreateSoundModule>() {
      public CreateSoundModule parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CreateSoundModule(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CreateSoundModule> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CreateSoundModule> getParserForType() {
      return PARSER;
    }

    public com.las4vc.composevr.protocol.Module.CreateSoundModule getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OnSoundModuleCreatedOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ComposeVR.OnSoundModuleCreated)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code ComposeVR.OnSoundModuleCreated}
   */
  public  static final class OnSoundModuleCreated extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ComposeVR.OnSoundModuleCreated)
      OnSoundModuleCreatedOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OnSoundModuleCreated.newBuilder() to construct.
    private OnSoundModuleCreated(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OnSoundModuleCreated() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OnSoundModuleCreated(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.las4vc.composevr.protocol.Module.internal_static_ComposeVR_OnSoundModuleCreated_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.las4vc.composevr.protocol.Module.internal_static_ComposeVR_OnSoundModuleCreated_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.las4vc.composevr.protocol.Module.OnSoundModuleCreated.class, com.las4vc.composevr.protocol.Module.OnSoundModuleCreated.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.las4vc.composevr.protocol.Module.OnSoundModuleCreated)) {
        return super.equals(obj);
      }
      com.las4vc.composevr.protocol.Module.OnSoundModuleCreated other = (com.las4vc.composevr.protocol.Module.OnSoundModuleCreated) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.las4vc.composevr.protocol.Module.OnSoundModuleCreated parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.las4vc.composevr.protocol.Module.OnSoundModuleCreated parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.las4vc.composevr.protocol.Module.OnSoundModuleCreated parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.las4vc.composevr.protocol.Module.OnSoundModuleCreated parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.las4vc.composevr.protocol.Module.OnSoundModuleCreated parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.las4vc.composevr.protocol.Module.OnSoundModuleCreated parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.las4vc.composevr.protocol.Module.OnSoundModuleCreated parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.las4vc.composevr.protocol.Module.OnSoundModuleCreated parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.las4vc.composevr.protocol.Module.OnSoundModuleCreated parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.las4vc.composevr.protocol.Module.OnSoundModuleCreated parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.las4vc.composevr.protocol.Module.OnSoundModuleCreated parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.las4vc.composevr.protocol.Module.OnSoundModuleCreated parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.las4vc.composevr.protocol.Module.OnSoundModuleCreated prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ComposeVR.OnSoundModuleCreated}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ComposeVR.OnSoundModuleCreated)
        com.las4vc.composevr.protocol.Module.OnSoundModuleCreatedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.las4vc.composevr.protocol.Module.internal_static_ComposeVR_OnSoundModuleCreated_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.las4vc.composevr.protocol.Module.internal_static_ComposeVR_OnSoundModuleCreated_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.las4vc.composevr.protocol.Module.OnSoundModuleCreated.class, com.las4vc.composevr.protocol.Module.OnSoundModuleCreated.Builder.class);
      }

      // Construct using com.las4vc.composevr.protocol.Module.OnSoundModuleCreated.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.las4vc.composevr.protocol.Module.internal_static_ComposeVR_OnSoundModuleCreated_descriptor;
      }

      public com.las4vc.composevr.protocol.Module.OnSoundModuleCreated getDefaultInstanceForType() {
        return com.las4vc.composevr.protocol.Module.OnSoundModuleCreated.getDefaultInstance();
      }

      public com.las4vc.composevr.protocol.Module.OnSoundModuleCreated build() {
        com.las4vc.composevr.protocol.Module.OnSoundModuleCreated result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.las4vc.composevr.protocol.Module.OnSoundModuleCreated buildPartial() {
        com.las4vc.composevr.protocol.Module.OnSoundModuleCreated result = new com.las4vc.composevr.protocol.Module.OnSoundModuleCreated(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.las4vc.composevr.protocol.Module.OnSoundModuleCreated) {
          return mergeFrom((com.las4vc.composevr.protocol.Module.OnSoundModuleCreated)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.las4vc.composevr.protocol.Module.OnSoundModuleCreated other) {
        if (other == com.las4vc.composevr.protocol.Module.OnSoundModuleCreated.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.las4vc.composevr.protocol.Module.OnSoundModuleCreated parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.las4vc.composevr.protocol.Module.OnSoundModuleCreated) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ComposeVR.OnSoundModuleCreated)
    }

    // @@protoc_insertion_point(class_scope:ComposeVR.OnSoundModuleCreated)
    private static final com.las4vc.composevr.protocol.Module.OnSoundModuleCreated DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.las4vc.composevr.protocol.Module.OnSoundModuleCreated();
    }

    public static com.las4vc.composevr.protocol.Module.OnSoundModuleCreated getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OnSoundModuleCreated>
        PARSER = new com.google.protobuf.AbstractParser<OnSoundModuleCreated>() {
      public OnSoundModuleCreated parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OnSoundModuleCreated(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OnSoundModuleCreated> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OnSoundModuleCreated> getParserForType() {
      return PARSER;
    }

    public com.las4vc.composevr.protocol.Module.OnSoundModuleCreated getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OpenBrowserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ComposeVR.OpenBrowser)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string device_type = 2;</code>
     */
    java.lang.String getDeviceType();
    /**
     * <code>string device_type = 2;</code>
     */
    com.google.protobuf.ByteString
        getDeviceTypeBytes();
  }
  /**
   * Protobuf type {@code ComposeVR.OpenBrowser}
   */
  public  static final class OpenBrowser extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ComposeVR.OpenBrowser)
      OpenBrowserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OpenBrowser.newBuilder() to construct.
    private OpenBrowser(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OpenBrowser() {
      deviceType_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OpenBrowser(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              deviceType_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.las4vc.composevr.protocol.Module.internal_static_ComposeVR_OpenBrowser_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.las4vc.composevr.protocol.Module.internal_static_ComposeVR_OpenBrowser_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.las4vc.composevr.protocol.Module.OpenBrowser.class, com.las4vc.composevr.protocol.Module.OpenBrowser.Builder.class);
    }

    public static final int DEVICE_TYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object deviceType_;
    /**
     * <code>string device_type = 2;</code>
     */
    public java.lang.String getDeviceType() {
      java.lang.Object ref = deviceType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceType_ = s;
        return s;
      }
    }
    /**
     * <code>string device_type = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceTypeBytes() {
      java.lang.Object ref = deviceType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDeviceTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, deviceType_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDeviceTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, deviceType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.las4vc.composevr.protocol.Module.OpenBrowser)) {
        return super.equals(obj);
      }
      com.las4vc.composevr.protocol.Module.OpenBrowser other = (com.las4vc.composevr.protocol.Module.OpenBrowser) obj;

      boolean result = true;
      result = result && getDeviceType()
          .equals(other.getDeviceType());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEVICE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.las4vc.composevr.protocol.Module.OpenBrowser parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.las4vc.composevr.protocol.Module.OpenBrowser parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.las4vc.composevr.protocol.Module.OpenBrowser parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.las4vc.composevr.protocol.Module.OpenBrowser parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.las4vc.composevr.protocol.Module.OpenBrowser parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.las4vc.composevr.protocol.Module.OpenBrowser parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.las4vc.composevr.protocol.Module.OpenBrowser parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.las4vc.composevr.protocol.Module.OpenBrowser parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.las4vc.composevr.protocol.Module.OpenBrowser parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.las4vc.composevr.protocol.Module.OpenBrowser parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.las4vc.composevr.protocol.Module.OpenBrowser parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.las4vc.composevr.protocol.Module.OpenBrowser parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.las4vc.composevr.protocol.Module.OpenBrowser prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ComposeVR.OpenBrowser}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ComposeVR.OpenBrowser)
        com.las4vc.composevr.protocol.Module.OpenBrowserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.las4vc.composevr.protocol.Module.internal_static_ComposeVR_OpenBrowser_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.las4vc.composevr.protocol.Module.internal_static_ComposeVR_OpenBrowser_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.las4vc.composevr.protocol.Module.OpenBrowser.class, com.las4vc.composevr.protocol.Module.OpenBrowser.Builder.class);
      }

      // Construct using com.las4vc.composevr.protocol.Module.OpenBrowser.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        deviceType_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.las4vc.composevr.protocol.Module.internal_static_ComposeVR_OpenBrowser_descriptor;
      }

      public com.las4vc.composevr.protocol.Module.OpenBrowser getDefaultInstanceForType() {
        return com.las4vc.composevr.protocol.Module.OpenBrowser.getDefaultInstance();
      }

      public com.las4vc.composevr.protocol.Module.OpenBrowser build() {
        com.las4vc.composevr.protocol.Module.OpenBrowser result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.las4vc.composevr.protocol.Module.OpenBrowser buildPartial() {
        com.las4vc.composevr.protocol.Module.OpenBrowser result = new com.las4vc.composevr.protocol.Module.OpenBrowser(this);
        result.deviceType_ = deviceType_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.las4vc.composevr.protocol.Module.OpenBrowser) {
          return mergeFrom((com.las4vc.composevr.protocol.Module.OpenBrowser)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.las4vc.composevr.protocol.Module.OpenBrowser other) {
        if (other == com.las4vc.composevr.protocol.Module.OpenBrowser.getDefaultInstance()) return this;
        if (!other.getDeviceType().isEmpty()) {
          deviceType_ = other.deviceType_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.las4vc.composevr.protocol.Module.OpenBrowser parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.las4vc.composevr.protocol.Module.OpenBrowser) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object deviceType_ = "";
      /**
       * <code>string device_type = 2;</code>
       */
      public java.lang.String getDeviceType() {
        java.lang.Object ref = deviceType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string device_type = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceTypeBytes() {
        java.lang.Object ref = deviceType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string device_type = 2;</code>
       */
      public Builder setDeviceType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string device_type = 2;</code>
       */
      public Builder clearDeviceType() {
        
        deviceType_ = getDefaultInstance().getDeviceType();
        onChanged();
        return this;
      }
      /**
       * <code>string device_type = 2;</code>
       */
      public Builder setDeviceTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceType_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ComposeVR.OpenBrowser)
    }

    // @@protoc_insertion_point(class_scope:ComposeVR.OpenBrowser)
    private static final com.las4vc.composevr.protocol.Module.OpenBrowser DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.las4vc.composevr.protocol.Module.OpenBrowser();
    }

    public static com.las4vc.composevr.protocol.Module.OpenBrowser getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OpenBrowser>
        PARSER = new com.google.protobuf.AbstractParser<OpenBrowser>() {
      public OpenBrowser parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OpenBrowser(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OpenBrowser> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OpenBrowser> getParserForType() {
      return PARSER;
    }

    public com.las4vc.composevr.protocol.Module.OpenBrowser getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MIDINoteOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ComposeVR.MIDINote)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes MIDI = 1;</code>
     */
    com.google.protobuf.ByteString getMIDI();
  }
  /**
   * Protobuf type {@code ComposeVR.MIDINote}
   */
  public  static final class MIDINote extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ComposeVR.MIDINote)
      MIDINoteOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MIDINote.newBuilder() to construct.
    private MIDINote(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MIDINote() {
      mIDI_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MIDINote(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              mIDI_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.las4vc.composevr.protocol.Module.internal_static_ComposeVR_MIDINote_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.las4vc.composevr.protocol.Module.internal_static_ComposeVR_MIDINote_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.las4vc.composevr.protocol.Module.MIDINote.class, com.las4vc.composevr.protocol.Module.MIDINote.Builder.class);
    }

    public static final int MIDI_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString mIDI_;
    /**
     * <code>bytes MIDI = 1;</code>
     */
    public com.google.protobuf.ByteString getMIDI() {
      return mIDI_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!mIDI_.isEmpty()) {
        output.writeBytes(1, mIDI_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!mIDI_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, mIDI_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.las4vc.composevr.protocol.Module.MIDINote)) {
        return super.equals(obj);
      }
      com.las4vc.composevr.protocol.Module.MIDINote other = (com.las4vc.composevr.protocol.Module.MIDINote) obj;

      boolean result = true;
      result = result && getMIDI()
          .equals(other.getMIDI());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MIDI_FIELD_NUMBER;
      hash = (53 * hash) + getMIDI().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.las4vc.composevr.protocol.Module.MIDINote parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.las4vc.composevr.protocol.Module.MIDINote parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.las4vc.composevr.protocol.Module.MIDINote parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.las4vc.composevr.protocol.Module.MIDINote parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.las4vc.composevr.protocol.Module.MIDINote parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.las4vc.composevr.protocol.Module.MIDINote parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.las4vc.composevr.protocol.Module.MIDINote parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.las4vc.composevr.protocol.Module.MIDINote parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.las4vc.composevr.protocol.Module.MIDINote parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.las4vc.composevr.protocol.Module.MIDINote parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.las4vc.composevr.protocol.Module.MIDINote parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.las4vc.composevr.protocol.Module.MIDINote parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.las4vc.composevr.protocol.Module.MIDINote prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ComposeVR.MIDINote}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ComposeVR.MIDINote)
        com.las4vc.composevr.protocol.Module.MIDINoteOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.las4vc.composevr.protocol.Module.internal_static_ComposeVR_MIDINote_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.las4vc.composevr.protocol.Module.internal_static_ComposeVR_MIDINote_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.las4vc.composevr.protocol.Module.MIDINote.class, com.las4vc.composevr.protocol.Module.MIDINote.Builder.class);
      }

      // Construct using com.las4vc.composevr.protocol.Module.MIDINote.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        mIDI_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.las4vc.composevr.protocol.Module.internal_static_ComposeVR_MIDINote_descriptor;
      }

      public com.las4vc.composevr.protocol.Module.MIDINote getDefaultInstanceForType() {
        return com.las4vc.composevr.protocol.Module.MIDINote.getDefaultInstance();
      }

      public com.las4vc.composevr.protocol.Module.MIDINote build() {
        com.las4vc.composevr.protocol.Module.MIDINote result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.las4vc.composevr.protocol.Module.MIDINote buildPartial() {
        com.las4vc.composevr.protocol.Module.MIDINote result = new com.las4vc.composevr.protocol.Module.MIDINote(this);
        result.mIDI_ = mIDI_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.las4vc.composevr.protocol.Module.MIDINote) {
          return mergeFrom((com.las4vc.composevr.protocol.Module.MIDINote)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.las4vc.composevr.protocol.Module.MIDINote other) {
        if (other == com.las4vc.composevr.protocol.Module.MIDINote.getDefaultInstance()) return this;
        if (other.getMIDI() != com.google.protobuf.ByteString.EMPTY) {
          setMIDI(other.getMIDI());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.las4vc.composevr.protocol.Module.MIDINote parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.las4vc.composevr.protocol.Module.MIDINote) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString mIDI_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes MIDI = 1;</code>
       */
      public com.google.protobuf.ByteString getMIDI() {
        return mIDI_;
      }
      /**
       * <code>bytes MIDI = 1;</code>
       */
      public Builder setMIDI(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mIDI_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes MIDI = 1;</code>
       */
      public Builder clearMIDI() {
        
        mIDI_ = getDefaultInstance().getMIDI();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ComposeVR.MIDINote)
    }

    // @@protoc_insertion_point(class_scope:ComposeVR.MIDINote)
    private static final com.las4vc.composevr.protocol.Module.MIDINote DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.las4vc.composevr.protocol.Module.MIDINote();
    }

    public static com.las4vc.composevr.protocol.Module.MIDINote getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MIDINote>
        PARSER = new com.google.protobuf.AbstractParser<MIDINote>() {
      public MIDINote parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MIDINote(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MIDINote> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MIDINote> getParserForType() {
      return PARSER;
    }

    public com.las4vc.composevr.protocol.Module.MIDINote getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ComposeVR_CreateSoundModule_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ComposeVR_CreateSoundModule_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ComposeVR_OnSoundModuleCreated_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ComposeVR_OnSoundModuleCreated_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ComposeVR_OpenBrowser_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ComposeVR_OpenBrowser_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ComposeVR_MIDINote_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ComposeVR_MIDINote_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Module.proto\022\tComposeVR\"&\n\021CreateSound" +
      "Module\022\021\n\tsender_id\030\001 \001(\t\"\026\n\024OnSoundModu" +
      "leCreated\"\"\n\013OpenBrowser\022\023\n\013device_type\030" +
      "\002 \001(\t\"\030\n\010MIDINote\022\014\n\004MIDI\030\001 \001(\014B;\n\035com.l" +
      "as4vc.composevr.protocol\252\002\031ComposeVR.Pro" +
      "tocol.Moduleb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ComposeVR_CreateSoundModule_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ComposeVR_CreateSoundModule_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ComposeVR_CreateSoundModule_descriptor,
        new java.lang.String[] { "SenderId", });
    internal_static_ComposeVR_OnSoundModuleCreated_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ComposeVR_OnSoundModuleCreated_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ComposeVR_OnSoundModuleCreated_descriptor,
        new java.lang.String[] { });
    internal_static_ComposeVR_OpenBrowser_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ComposeVR_OpenBrowser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ComposeVR_OpenBrowser_descriptor,
        new java.lang.String[] { "DeviceType", });
    internal_static_ComposeVR_MIDINote_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ComposeVR_MIDINote_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ComposeVR_MIDINote_descriptor,
        new java.lang.String[] { "MIDI", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
